Допустим, у нас есть класс, который выполняет некоторые операции с числами, и мы хотим создать своё исключение, которое
будет выбрасываться в случае, если операция не может быть выполнена с заданными аргументами. Для этого можно создать
собственный класс исключения. Например, так:

```java
public class InvalidArgumentsException extends Exception {
    public InvalidArgumentsException(String errorMessage) {
        super(errorMessage);
    }
}
```

Затем в методе, который выполняет операции с числами, мы можем выбросить это исключение, если аргументы не соответствуют
нашим требованиям. Например:

```java
public static int divide(int a,int b)throws InvalidArgumentsException{
        if(b==0){
        throw new InvalidArgumentsException("Divisor cannot be zero");
        }
        return a/b;
        }
```

Здесь мы выбрасываем исключение, если аргумент b равен 0.

Затем мы можем перехватить это исключение в блоке try-catch и обработать его. Например:

```java
try{
        int result=divide(10,0);
        System.out.println("Result: "+result);
        }catch(InvalidArgumentsException e){
        System.out.println("Error: "+e.getMessage());
        }
```

Здесь мы вызываем метод divide(10, 0), который выбросит исключение, и затем перехватываем его в блоке catch и выводим
сообщение об ошибке.